# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

install! 'cocoapods', :deterministic_uuids => false

target 'Base' do

pod 'Fabric'
pod 'Crashlytics'
pod 'Branch'
pod 'VTAcknowledgementsViewController'
pod 'SwiftMessages'
pod 'PKHUD', '~> 4.0'
pod 'SDWebImage', '~>3.8'
pod 'JSQWebViewController'
pod 'IQKeyboardManagerSwift'
pod 'SwiftColor'
pod 'Fabric'
pod 'Crashlytics'
pod 'SwiftyJSON'
pod 'Alamofire', '~> 4.0'
pod 'ObjectMapper', '~> 2.2'
pod 'Fakery'

end

target 'BaseTests' do

pod 'SwiftyJSON'
pod 'Alamofire', '~> 4.0'
pod 'ObjectMapper', '~> 2.2'
pod 'Fakery'

end

#   Disable Code Coverage for Pods projects
post_install do |installer_representation|
   installer_representation.pods_project.targets.each do |target|
       target.build_configurations.each do |config|
            config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
       end
   end
end
