# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target ‘Base’ do

pod 'Fabric'
pod 'Crashlytics'
pod 'VTAcknowledgementsViewController'
pod 'SwiftMessages'
pod 'PKHUD', '~> 4.0'
pod 'SDWebImage', '~>3.8'
pod 'JSQWebViewController'
pod 'IQKeyboardManagerSwift'
pod 'SwiftColor'
pod 'Fabric'
pod 'Crashlytics'
pod 'SwiftyJSON'
pod 'Alamofire', '~> 4.0'
pod 'ObjectMapper', '~> 2.2'

end
